### ISSUE TITLE
Very minor spelling correction (README, comment lines only)...

### ISSUE THREAD

**Issue by wrycoder** [rdormer/spiderkit#1]
This looks like a really useful package. I just have one minor issue with the documentation & comments. Here's a simple guideline to remember:

"IT'S" == "it is"
"ITS" == "something belongs to it"

I think I have found all the instances of this error. (I believe they were only in comments and documentation.)

[spiderkit_diff.txt](https://github.com/rdormer/spiderkit/files/1176259/spiderkit_diff.txt)

**Comment by rdormer** [comment]
Thanks for the heads up!
